export const GET_USER_REPOS_REQUEST = 'app/UserRepos/GET_USER_REPOS_REQUEST';
export const GET_USER_REPOS_SUCCESS = 'app/UserRepos/GET_USER_REPOS_SUCCESS';
export const GET_USER_REPOS_ERROR = 'app/UserRepos/GET_USER_REPOS_ERROR';