export const AUTH_LOGIN_REQUEST = 'app/auth/AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'app/auth/AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_ERROR = 'app/auth/AUTH_LOGIN_ERROR'
export const AUTH_REGISTER_REQUEST = 'app/auth/AUTH_REGISTER_REQUEST'
export const AUTH_REGISTER_SUCCESS = 'app/auth/AUTH_REGISTER_SUCCESS'
export const AUTH_REGISTER_ERROR = 'app/auth/AUTH_REGISTER_ERROR'
export const AUTH_LOGOUT = 'app/auth/AUTH_LOGOUT'
export const AUTH_SELLER_REQUEST = 'app/auth/AUTH_SELLER_REQUEST'
export const AUTH_SELLER_SUCCESS = 'app/auth/AUTH_SELLER_SUCCESS'
export const AUTH_SELLER_ERROR = 'app/auth/AUTH_SELLER_ERROR'
export const AUTH_RESET_PASSWORD_REQUEST =
	'app/auth/AUTH_RESET_PASSWORD_REQUEST'
export const AUTH_RESET_PASSWORD_SUCCESS =
	'app/auth/AUTH_RESET_PASSWORD_SUCCESS'
export const AUTH_RESET_PASSWORD_ERROR = 'app/auth/AUTH_RESET_PASSWORD_ERROR'
export const AUTH_RESTORE_PASSWORD_REQUEST =
	'app/auth/AUTH_RESTORE_PASSWORD_REQUEST'
export const AUTH_RESTORE_PASSWORD_SUCCESS =
	'app/auth/AUTH_RESTORE_PASSWORD_SUCCESS'
export const AUTH_RESTORE_PASSWORD_ERROR =
	'app/auth/AUTH_RESTORE_PASSWORD_ERROR'
export const GET_ALL_MARKETPLACE_REQUEST =
	'app/auth/GET_ALL_MARKETPLACE_REQUEST'
export const GET_ALL_MARKETPLACE_SUCCESS =
	'app/auth/GET_ALL_MARKETPLACE_SUCCESS'
export const GET_ALL_MARKETPLACE_ERROR = 'app/auth/GET_ALL_MARKETPLACE_ERROR'
